general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

general.live_config_reload = true


[window]
padding = { x = 4, y = 10 }
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 14.0

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
osc52 = "CopyPaste"
shell = "/bin/zsh"

[env]
TERM = "xterm-256color"
